### PR TITLE
fix: skip unmasking overlay deps already installed from other repos

### LINKED ISSUE #1: Ebuild conflicts from different overlays
When an overlay is added its ebuilds may get conflicted with other ebuilds' dependencies,

e.g. when installing `net-libs/nodejs` while **ambasta** overlay is enabled for an another package, it will conflict with **gentoo**'s `net-libs/nodejs` and would fail any update for `nodejs` since they got different use flags, and some packages are already dependent on **gentoo**'s `nodejs`'s version.

### PR DESCRIPTION
**Pull request by 0xjah**
## Summary

Prevents dependency conflicts when an overlay is enabled for a specific package but its dependencies are already installed from another repository (e.g., gentoo).

## Problem

When installing a package from an overlay (e.g., ambasta), all its dependencies were being unmasked from that overlay. This caused conflicts when packages like `net-libs/nodejs` were already installed from the gentoo repo with different USE flags, breaking updates and other dependent packages.

Closes #1 

## Solution

Added `isInstalledFromOtherRepo()` function that:
- Checks `/var/db/pkg/` for installed packages
- Reads the `repository` file to determine the source repo
- Skips unmasking overlay dependencies that are already installed from a different repository

This ensures the system uses existing packages from their original repos instead of trying to switch to overlay versions.

## Example

Before: Installing `app-foo/bar` from `ambasta` would unmask:
```
net-libs/nodejs::ambasta  # Conflicts with gentoo's nodejs
```

After: If `net-libs/nodejs` is installed from `gentoo`, it stays masked from `ambasta` and the existing gentoo version is used.

### CODE REVIEW

File: actions/enable_repo_for_package.go [hunk 1]
```diff
@@ -100,12 +101,58 @@ func (e *EnableRepoForPackageAction) unmaskDeps() error {
...
+	// Check /var/db/pkg for installed packages
+	parts := strings.SplitN(pkgName, "/", 2)
+	if len(parts) != 2 {
+		return false
+	}
+	pkgDir := "/var/db/pkg/" + parts[0]
+	entries, err := os.ReadDir(pkgDir)
+	if err != nil {
+		return false
+	}
```
Comment (mbaraa) [inline actions/enable_repo_for_package.go]: Instead of splitting to find the package's pair, you can just pass the package's (ebuild) `GroupName` along with the package name to this function, as every ebuild is guaranteed to have a group name.

File: actions/enable_repo_for_package.go [hunk 2]
```diff
@@ -100,12 +101,58 @@ func (e *EnableRepoForPackageAction) unmaskDeps() error {
...
+		repoFile := pkgDir + "/" + entry.Name() + "/repository"
+		data, err := os.ReadFile(repoFile)
+		if err != nil {
+			continue
+		}
+		repo := strings.TrimSpace(string(data))
+		if repo != "" && repo != overlayName {
+			return true // Installed from different repo, skip overlay version
+		}
+	}
```
Comment (mbaraa) [inline actions/enable_repo_for_package.go]: No need for iterating over the ebuild's directory to find the `repository` file, you can just open directly.
```go
...
os.ReadFile(fmt.Sprtintf("/var/db/pkg/%s/%s", goupName, pkgName))
...
```

**Review by mbaraa — CHANGES_REQUESTED** [review]
Left some comments 🥦

**Comment by mbaraa** [comment]
Hey @0xjah, thanks for reaching out to help, I like the idea of your solution, but left some comments to make it more elegant, and I would appreciate it if you reduce the LLM-style comments.

**Review by mbaraa — APPROVED** [review]

**Comment by mbaraa** [comment]
Thanks for your contribution, @0xjah, consider starring the repo to make it look cooler with stars!
